Library/Library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("", include("books.urls", namespace="books")),
]

Library/books/urls.py
from django.urls import path
from . import views

# root url: books/
app_name = "books"
urlpatterns = [
    path("", views.get_authors, name="get_authors"),
    path("get/book/infor/ma/tion/", views.getBookInfo, name="getBookInfo"),
    path("<author_tag>/", views.get_books, name="get_books"),
    path("<author_tag>/<book_tag>/", views.get_chapters, name="get_chapters"),
    path(
        "<author_tag>/<book_tag>/<chapter_id>",
        views.get_chapter_content,
        name="get_content",
    ),
    path(
        "<author_tag>/<book_tag>/<chapter_id>/<next_previous>",
        views.get_next_previous,
        name="next_previous",
    ),
]

Library/users/urls.py
from django.urls import path
from . import views


app_name = "users"
urlpatterns = [
    ## user login system
    path("login/", views.login, name="login"),
    path("register/", views.register, name="register"),
    path("userverify/", views.userverify, name="userverify"),
    path("mine/", views.mine, name="mine"),
    path("logout/", views.logout, name="logout"),
    ## booklist system
    path("createBookList/", views.createBookList, name="createbooklist"),
    path("getUserBookLists/", views.getUserBookLists, name="getUserBookLists"),
    path("getBookList/", views.getBookList, name="getBookList"),
    path("deleteBookList/", views.deleteBookList, name="deleteBookList"),
    path("addBookToList/", views.addBookToList, name="addBookToList"),
    path("deleteBookFromList/", views.deleteBookFromList, name="deleteBookFromList"),
    ##shopping cart system
    path("addbooktocart/", views.addBookToCart, name="addBookToCart"),
    path("getshoppingcart/", views.getshoppingcart, name="getshoppingcart"),
]

Library/books/models.py
from unittest.util import _MAX_LENGTH
from django.db import models

# Create your models here.
class Author(models.Model):
    author_tag = models.CharField(max_length = 255, primary_key=True)
    author_name = models.CharField(max_length = 255)

class Book(models.Model):
    book_tag = models.CharField(max_length = 255, primary_key=True)
    book_name = models.CharField(max_length = 255)
    author_tag = models.CharField(max_length = 255)
    # # to delete the book when the author is deleted-- cascading
    # author_tag = models.ForeignKey(Author, on_delete=models.CASCADE)

class Chapter(models.Model):
    chapter_index = models.CharField(max_length = 255)
    chapter_name= models.CharField(max_length = 255)
    book_tag = models.CharField(max_length = 255)
    chapter_content= models.TextField(default='SOME STRING')
    # book_tag = models.ForeignKey(Book, on_delete=models.CASCADE )

Library/books/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse, HttpResponseNotFound
from books.models import Author, Book, Chapter
from django.http import HttpResponseRedirect
import sys
import os
import util

# Create your views here.
def get_authors(request):
    authors = Author.objects.order_by("author_name")

    if authors.exists():
        data = {"authors": authors}
        return render(request, "books/authorslist.html", context=data)

    return util.handler404(request)


def get_books(request, author_tag):

    books = Book.objects.filter(author_tag=author_tag)

    if books.exists():
        author_name = get_author_name(author_tag)
        data = {"books": books, "author_tag": author_tag, "author_name": author_name}

        return render(request, "books/booklist.html", context=data)

    return util.handler404(request)


def get_chapters(request, author_tag, book_tag):
    chapters = (
        Chapter.objects.filter(book_tag=book_tag)
        .defer("chapter_content")
        .order_by("chapter_index")
    )
    if chapters.exists():
        book_name = get_book_name(book_tag)
        data = {"chapters": chapters, "author_tag": author_tag, "book_name": book_name}

        return render(request, "books/chapterlist.html", context=data)

    return util.handler404(request)


def get_chapter_content(request, author_tag, book_tag, chapter_id):

    if not chapter_id.isdigit():
        return util.handler404(request)

    chapter = Chapter.objects.filter(id=chapter_id).first()

    if chapter:
        book_name = get_book_name(book_tag)
        data = {"chapter": chapter, "author_tag": author_tag, "book_name": book_name}

        return render(request, "books/chaptercontent.html", context=data)

    return util.handler404(request)


def get_next_previous(request, author_tag, book_tag, chapter_id, next_previous):
    chapters = (
        Chapter.objects.filter(book_tag=book_tag)
        .defer("chapter_content")
        .order_by("chapter_index")
    )

    # print(type(next_previous), type(0))
    if next_previous == "0":
        chapters = chapters.reverse()

    chapterslist = list(chapters)

    isFound = 0

    book_name = get_book_name(book_tag)
    data = {}
    for chapter in chapterslist:
        if isFound == 1:
            data["chapter"] = chapter
            data["author_tag"] = author_tag
            data["book_name"] = book_name
            return render(request, "books/chaptercontent.html", context=data)
        if str(chapter.id) == chapter_id:
            data["chapter"] = chapter
            data["author_tag"] = author_tag
            data["book_name"] = book_name
            # print("Found")
            isFound = 1

    return render(request, "books/chaptercontent.html", context=data)


def get_author_name(author_tag):
    res_name = Author.objects.filter(author_tag=author_tag).only("author_name").first()
    return res_name.author_name


def get_book_name(book_tag):
    res_name = Book.objects.filter(book_tag=book_tag).only("book_name").first()
    return res_name.book_name


def getBookInfo(request):
    book_tag = request.GET.get("book_tag")
    book = list(Book.objects.filter(book_tag=book_tag).values())
    data = {}
    data["book"] = book
    return JsonResponse(data=data)

Library/templates/books/authorslist.html
{% extends 'base.html'%} {% load static %} {% block css %} {{ block.super }}

<link rel="stylesheet" href="{% static 'books/css/authorslist.css'%}" />
{% endblock %} {% block content %}

<div class="off_canvas">
  <button
    class="menu_button"
    data-bs-toggle="offcanvas"
    href="#offcanvasExample"
    role="button"
    aria-controls="offcanvasExample"
  ></button>

  <div
    class="offcanvas offcanvas-start"
    tabindex="-1"
    id="offcanvasExample"
    aria-labelledby="offcanvasExampleLabel"
  >
    <div class="offcanvas-body">
      <a href="{% url 'users:mine' %}"> Mine </a>
      </br>
      <a href="{% url "users:logout" %}">Log out</a>
    </div>
  </div>
</div>

<div class="title">Author List</div>
<div class="authorslist">
  <ul>
    {%for author in authors%}
    <li>
      <a
        href="{% url 'books:get_books' author.author_tag %}"
        class="authors_link"
        >{{author.author_name}}
      </a>
    </li>

    {% endfor %}
  </ul>
</div>
{% endblock %}

Library/templates/books/booklist.html
{% extends 'base.html'%} {% load static %} 
{% block css %} {{ block.super }}
<link rel="stylesheet" href="{% static 'books/css/booklist.css'%}" />
{% endblock %}

{% block scripts%} {{ block.super }}

<script type="text/javascript" src="{% static 'books/js/books.js' %}"></script>

{% endblock %} {% block content %}

<div>
  <div class="off_canvas">
      <button  class="  menu_button" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
        
      </button>

      <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
        <div class="offcanvas-body">
          <a href="{% url 'users:mine' %}"> Mine </a>
          </br>
          <a href="{% url 'books:get_authors'%}"> Back to Author List</a>
          </br>
          <a href="{% url "users:logout" %}">Log out</a>
        </div>
      </div>

  </div>
  <h1 class="title">{{author_name}} Book List</h1>
  <div class="bookslistdiv">
    <ul >
      {% for book in books %}
      <li>
      <div>
        <a
          id="book_name"
          href="{% url 'books:get_chapters' author_tag book.book_tag %}"
          >{{book.book_name}}
        </a>
        <button
          type="button"
          class="btn btn-outline-secondary btn-sm"
          data-bs-target="#exampleModal"
          data-bs-whatever="{{book.book_name}}"
          onClick="return Add_to_List_Modal('{{book.book_name}}','{{book.book_tag}}')"
        >
          Add to List
        </button> 
      </div> 
      </li>
      {% endfor %}
    </ul>
  </div>
 
</div>

<!-- Modal -->
<div
  class="modal fade"
  id="exampleModal"
  data-bs-backdrop="static"
  data-bs-keyboard="false"
  tabindex="-1"
  aria-hidden="true"
>
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
        <h5 hidden class ="modal-book-tag" name="modal-book-tag" id = "modal-book-tag"> book tag  </h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
      <ul id="book_list">
      </ul>
      </div>
      <div>
        <button
          type="button"
          class="btn btn-outline-dark btn-sm add_button"
          onClick="return Add_to_List()"
        >
          +
        </button>
        <input name="booklist_title" id="booklist_title" placeholder="New List Title"></input>
         <div id="add_booklist_info"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-dark btn-sm" data-bs-dismiss="modal">
          Done
        </button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

Library/templates/books/chaptercontent.html
{% extends 'base.html'%} {% load static %} {% block css %} {{ block.super }}

<link rel="stylesheet" href="{% static 'books/css/chaptercontent.css'%}" />
{% endblock %} {% block content %}
<div>

<div class="off_canvas">
    <button
      class="menu_button"
      data-bs-toggle="offcanvas"
      href="#offcanvasExample"
      role="button"
      aria-controls="offcanvasExample"
    ></button>

    <div
      class="offcanvas offcanvas-start"
      tabindex="-1"
      id="offcanvasExample"
      aria-labelledby="offcanvasExampleLabel"
    >
      <div class="offcanvas-body">
        <a href="{% url 'users:mine' %}"> Mine </a>
        </br>
         <a href="{% url 'books:get_chapters' author_tag chapter.book_tag%}">
    Back to Book
  </a>
        </br>
        <a
    href="{% url 'books:next_previous' author_tag chapter.book_tag chapter.id 1%}"
    >Next Chapter</a
  >
  </br>

  <a
    href="{% url 'books:next_previous' author_tag chapter.book_tag chapter.id 0%}"
    >Previous Chapter</a
  >
  </br>
      <a href="{% url "users:logout" %}">Log out</a>
      </div>

    </div>
  </div>
  <h1 class="title">{{book_name}} {{chapter.chapter_name}}</h1>
 


  <p class="chaptercontent">{{chapter.chapter_content}}</p>
</div>
{% endblock %}

Library/templates/books/chapterlist.html
{% extends 'base.html'%} {% load static %} {% block css %} {{ block.super }}

<link rel="stylesheet" href="{% static 'books/css/chapterlist.css'%}" />
{% endblock %} {% block content %}
<div>
  <div class="off_canvas">
    <button
      class="menu_button"
      data-bs-toggle="offcanvas"
      href="#offcanvasExample"
      role="button"
      aria-controls="offcanvasExample"
    ></button>

    <div
      class="offcanvas offcanvas-start"
      tabindex="-1"
      id="offcanvasExample"
      aria-labelledby="offcanvasExampleLabel"
    >
      <div class="offcanvas-body">
        <a href="{% url 'users:mine' %}"> Mine </a>
        </br>
        <a href="{% url 'books:get_authors'%}"> Back to Author List</a>
        </br>
        <a href="{% url 'books:get_books' author_tag%}"> Back to Book List</a>
        </br>
      <a href="{% url "users:logout" %}">Log out</a>
      </div>
    </div>
  </div>

  <h1 class="title">{{book_name}} Chapter List</h1>

  <div class="chapterlist">
    <ul>
      {% for chapter in chapters%}
      <li>
        <a
          href="{% url 'books:get_content' author_tag chapter.book_tag chapter.id%}"
        >
          {{chapter.chapter_name}}
        </a>
      </li>
      {% endfor%}
    </ul>
  </div>
</div>
{% endblock %}